//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_List
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Shop
    {
        public int id { get; set; }
        public string Документ { get; set; }
        public int Номер_заказа { get; set; }
        public string Номер_детали { get; set; }
        public int Количество { get; set; }
        public string Машинное_время { get; set; }
        public System.DateTime Дата { get; set; }
        public string Комментарий { get; set; }
    }
}
